/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author tengk
 */
public class ManageRoster extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageRoster.class.getName());

    /**
     * Creates new form ManageRoaster
     */
    public ManageRoster() {
        initComponents();
        rosterList.setEditable(false);
        loadRoster();
    }
    
    private void loadRoster()
    {
        File file = new File("roster.txt");
        rosterList.setText("");
        
        if(!file.exists())
        {
            rosterList.setText("No roster records found");
            return;
        }
        
        try
        {
            Scanner input = new Scanner(file);
            while(input.hasNextLine())
            {
                String line = input.nextLine();
                rosterList.append(line+"\n");
            }
            input.close();
        }
        
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this,"Unable to read records");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRosterID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDoctorID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtShiftDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rosterList = new javax.swing.JTextArea();
        cmbShiftType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Doctor Shift Roster");

        jLabel2.setText("RosterID:");

        jLabel3.setText("DoctorID:");

        jLabel4.setText("Shift Date:");

        jLabel5.setText("Shift Type:");

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        rosterList.setColumns(20);
        rosterList.setRows(5);
        jScrollPane1.setViewportView(rosterList);

        cmbShiftType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning(05:00-12:00)", "Afternoon(12:00-19:00)", "Night(19:00-05:00)" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDoctorID)
                                .addComponent(txtRosterID)
                                .addComponent(txtShiftDate, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                            .addComponent(cmbShiftType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(88, 88, 88)
                        .addComponent(btnUpdate)
                        .addGap(95, 95, 95)
                        .addComponent(btnAdd)))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRosterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtShiftDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbShiftType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdate)
                        .addComponent(btnAdd)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ManagerDashboard dashboard = new ManagerDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String rosterID = txtRosterID.getText().trim().toUpperCase();
        String doctorID = txtDoctorID.getText().trim().toUpperCase();
        String shiftDate = txtShiftDate.getText().trim();
        String shiftType = cmbShiftType.getSelectedItem().toString();
        
        //check empty 
        if(rosterID.isEmpty()||doctorID.isEmpty()||shiftDate.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please complete all fields");
            return;
        }
        
        //check ID
        if(!rosterID.matches("R\\d{3}"))
        {
            JOptionPane.showMessageDialog(this, "RosterID must be RXXX");
            txtRosterID.requestFocus();
            return;
        }
        if(!doctorID.matches("D\\d{3}"))
        {
            JOptionPane.showMessageDialog(this, "DoctorID must be DXXX");
            txtDoctorID.requestFocus();
            return;
        }
        
        if(rosterIDExists(rosterID))
        {
            JOptionPane.showMessageDialog(this, "RosterID already exists");
            txtRosterID.requestFocus();
            return;
        }
        
        if(!ValidDate(shiftDate))
        {
            JOptionPane.showMessageDialog(this,"Please enter a valid date.Example:dd/mm/yyyy");
            txtShiftDate.requestFocus();
            return;
        }
        
        if(shiftExists(doctorID,shiftDate,shiftType))
        {
            JOptionPane.showMessageDialog(this, "This doctor already have same shift on this date");
            return;
        }
        
        try
        {
            FileWriter writer = new FileWriter("roster.txt",true);
            writer.write("RosterID:"+rosterID+"\n");
            writer.write("DoctorID:"+doctorID+"\n");
            writer.write("ShiftDate:"+shiftDate+"\n");
            writer.write("ShiftType:"+shiftType+"\n");
            writer.close();
            JOptionPane.showMessageDialog(this, "Roster added successfully");
            
            txtRosterID.setText("");
            txtDoctorID.setText("");
            txtShiftDate.setText("");
            cmbShiftType.setSelectedIndex(0);
            
            loadRoster();
        }
        
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this,"Unable to add the roster");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String rosterID = txtRosterID.getText().trim().toUpperCase();
        String doctorID = txtDoctorID.getText().trim().toUpperCase();
        String shiftDate = txtShiftDate.getText().trim();
        String shiftType = cmbShiftType.getSelectedItem().toString();
        
        //check empty
        if(rosterID.isEmpty()||doctorID.isEmpty()||shiftDate.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please complete all fields");
            return;
        }
        
        //check ID
        if(!rosterID.matches("R\\d{3}"))
        {
            JOptionPane.showMessageDialog(this, "RosterID must be RXXX");
            txtRosterID.requestFocus();
            return;
        }
        if(!doctorID.matches("D\\d{3}"))
        {
            JOptionPane.showMessageDialog(this, "DoctorID must be DXXX");
            txtDoctorID.requestFocus();
            return;
        }
        
        //check Date and Type
        if(!ValidDate(shiftDate))
        {
            JOptionPane.showMessageDialog(this,"Please enter a valid date.Example:dd/mm/yyyy");
            txtShiftDate.requestFocus();
            return;
        }
        if(shiftExistsForUpdate(rosterID,doctorID,shiftDate,shiftType))
        {
            JOptionPane.showMessageDialog(this,"This doctor already has a same Shift on this date");
            return;
        }
        
        File file = new File("roster.txt");
        if(!file.exists())
        {
            JOptionPane.showMessageDialog(this, "No roster record found");
            return;
        }
        
        StringBuilder updateData = new StringBuilder();
        boolean rosterFound = false;
        
        try
        {
            Scanner input = new Scanner(file);
            
            while(input.hasNextLine())
            {
                String line = input.nextLine();
                
                if(line.equalsIgnoreCase("RosterID:"+rosterID))
                {
                    rosterFound = true;
                    updateData.append("RosterID:"+rosterID+"\n");
                    
                    if(input.hasNextLine())
                    {
                        input.nextLine();
                    }
                    
                    if(input.hasNextLine())
                    {
                        input.nextLine();
                    }
                    if(input.hasNextLine())
                    {
                        input.nextLine();
                    }
                    updateData.append("DoctorID:"+doctorID+"\n");
                    updateData.append("ShiftDate:"+shiftDate+"\n");
                    updateData.append("ShiftType:"+shiftType+"\n");
                }
                else
                {
                    updateData.append(line+"\n");
                }
            }
            input.close();
            
            if(!rosterFound)
            {
                JOptionPane.showMessageDialog(this,"RosterID not Found");
                return;
            }
            
            FileWriter writer = new FileWriter("roster.txt");
            writer.write(updateData.toString());
            writer.close();
            JOptionPane.showMessageDialog(this,"Roster updated successfully");
            
            txtRosterID.setText("");
            txtDoctorID.setText("");
            txtShiftDate.setText("");
            cmbShiftType.setSelectedIndex(0);
            
            loadRoster();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this,"Unable to update the roster");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private boolean ValidDate(String shiftDate)
    {
        if(!shiftDate.matches("\\d{2}/\\d{2}/\\d{4}"))
        {
            return false;
        }
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        format.setLenient(false);
        
        try
        {
            format.parse(shiftDate);
            return true;
        }
        
        catch(ParseException e)
        {
            return false;
        }
    }
        
    private boolean rosterIDExists(String rosterID)
    {
        File file = new File("roster.txt");
        
        if(!file.exists())
        {
            return false;
        }
        
        try
        {
            Scanner input = new Scanner(file);
            
            while(input.hasNextLine())
            {
                String line = input.nextLine().trim();
                
                
                if(line.equalsIgnoreCase("RosterID:"+rosterID))
                {
                    input.close();
                    return true;
                }
            }
        input.close();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this,"Unable to read records");
        }
        return false;
    } 
    
    private boolean shiftExists(String doctorID,String shiftDate,String shiftType)
    {
        File file = new File("roster.txt");
        
        if(!file.exists())
        {
            return false;
        }
        try
        {
            Scanner input = new Scanner(file);
            
            while(input.hasNextLine())
            {
                String line = input.nextLine().trim();
                if(line.startsWith("RosterID:"))
                {
                    //Read line
                    String doctorLine = input.nextLine().trim();
                    String dateLine = input.nextLine().trim();
                    String shiftLine = input.nextLine().trim();
                    
                        //compare with user input to check
                        if((doctorLine.equalsIgnoreCase("DoctorID:" + doctorID)
                           &&dateLine.equalsIgnoreCase("ShiftDate:" + shiftDate)
                           && shiftLine.equalsIgnoreCase("ShiftType:" + shiftType)))
                        {
                            input.close();
                            return true;
                        }
                }
            }
            input.close();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this,"Unable to check existing shifts");
        }
        return false;
    }
    
    private boolean shiftExistsForUpdate(String rosterID,String doctorID,String shiftDate,String shiftType)
    {
    File file = new File("roster.txt");

    if(!file.exists())
    {
        return false;
    }

    try
    {
        Scanner input = new Scanner(file);

        while(input.hasNextLine())
        {
            String rosterLine = input.nextLine().trim();

            if(rosterLine.startsWith("RosterID:"))
            {
                String doctorLine = input.nextLine().trim();
                String dateLine = input.nextLine().trim();
                String shiftLine = input.nextLine().trim();

                // Ignore the roster currently being updated
                if(!rosterLine.equalsIgnoreCase("RosterID:" + rosterID))
                {
                    if(doctorLine.equalsIgnoreCase("DoctorID:" + doctorID)
                       &&dateLine.equalsIgnoreCase("ShiftDate:" + shiftDate)
                       &&shiftLine.equalsIgnoreCase("ShiftType:" + shiftType))
                    {
                        input.close();
                        return true;
                    }
                }
            }
        }

        input.close();
    }
    catch(IOException e)
    {
        JOptionPane.showMessageDialog(this,
                "Unable to check existing shifts");
    }

    return false;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageRoster().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbShiftType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea rosterList;
    private javax.swing.JTextField txtDoctorID;
    private javax.swing.JTextField txtRosterID;
    private javax.swing.JTextField txtShiftDate;
    // End of variables declaration//GEN-END:variables
}
