/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package managementsystem;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;        
/**
 *
 * @author tengk
 */
public class ManageDepartment extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageDepartment.class.getName());

    /**
     * Creates new form ManageDepartment
     */
    public ManageDepartment() 
    {
        initComponents();
        Departmentlist.setEditable(false);
        loadDepartments();
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Departmentlist = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Clinical Department Management");

        jLabel2.setText("Department ID: ");

        jLabel3.setText("Department Name:");

        jLabel4.setText("Description:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        Departmentlist.setColumns(20);
        Departmentlist.setRows(5);
        jScrollPane1.setViewportView(Departmentlist);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addGap(46, 46, 46)
                                .addComponent(btnAdd))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(btnBack)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ManagerDashboard dashboard = new ManagerDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String departmentID = txtID.getText().trim().toUpperCase();
        String departmentName = txtName.getText().trim();
        String description = txtDescription.getText().trim();
        
        //check empty
        if(departmentID.isEmpty()||departmentName.isEmpty()||description.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please complete all fields");
            return;
        }
        
        //check ID
        if(!departmentID.matches("D\\d{3}"))
        {
            JOptionPane.showMessageDialog(this,"Department must be DXXX");
            txtID.requestFocus();
            return;
        }
        
        if(departmentIDExists(departmentID))
        {
            JOptionPane.showMessageDialog(this,"Department ID already exists");
            txtID.requestFocus();
            return;
        }
        
        //check name
        if(!departmentName.matches("[a-zA-Z '&-]+"))
        {
            JOptionPane.showMessageDialog(this,"Name must be contain letters only");
            txtName.requestFocus();
            return;
        }
        
        try
        {
            FileWriter writer = new FileWriter("department.txt",true);
            writer.write("DepartmentID:"+departmentID+"\n");
            writer.write("DepartmentName:"+departmentName+"\n");
            writer.write("Description:"+description+"\n");
            writer.close();
            JOptionPane.showMessageDialog(this,"Added successfully");
            
            //set empty text after add
            txtID.setText("");
            txtName.setText("");
            txtDescription.setText("");
            
            loadDepartments();
        }

        
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this,"Unable to Add the Department");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String departmentID = txtID.getText().trim().toUpperCase();
        String departmentName = txtName.getText().trim();
        String description = txtDescription.getText().trim();
        
        //check ID
        if(departmentID.isEmpty()||departmentName.isEmpty()||description.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please complete all fields");
            return;
        }
        
        if(!departmentID.matches("D\\d{3}"))
        {
            JOptionPane.showMessageDialog(this,"Department ID must be DXXX");
            txtID.requestFocus();
            return;
        }
        
        //check name
        if(!departmentName.matches("[a-zA-Z '&-]+"))
        {
            JOptionPane.showMessageDialog(this,"Name must be contain letters only");
            txtName.requestFocus();
            return;
        }
        
        File file = new File("department.txt");
        if(!file.exists())
        {
            JOptionPane.showMessageDialog(this,"No department records found");
            return;
        }
        
        StringBuilder updateData = new StringBuilder();
        boolean departmentFound = false;
        
        try
        {
            Scanner input = new Scanner(file);
            
            while(input.hasNextLine())
            {
                String line = input.nextLine();
                
                if(line.equalsIgnoreCase("DepartmentID:"+departmentID))
                {
                    departmentFound = true;
                    updateData.append("DepartmentID:"+departmentID+"\n");
                    
                    if(input.hasNextLine())
                    {
                        input.nextLine();
                    }
                    
                    if(input.hasNextLine())
                    {
                        input.nextLine();
                    }
                    
                    updateData.append("DepartmentName:"+departmentName+"\n");
                    updateData.append("Description:"+description+"\n");
                }
                else
                {
                    updateData.append(line+"\n");
                }
            }
            input.close();
            
            if(!departmentFound)
            {
                JOptionPane.showMessageDialog(this,"DepartmentID not Found");
                return;
            }
            
            FileWriter writer = new FileWriter("department.txt");
            writer.write(updateData.toString());
            writer.close();
            JOptionPane.showMessageDialog(this,"Department updated successfully");
            
            txtID.setText("");
            txtName.setText("");
            txtDescription.setText("");
            
            loadDepartments();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this,"Unable to update the department");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void loadDepartments()
    {
        File file = new File("department.txt");
        
        Departmentlist.setText("");
        
        if(!file.exists())
        {
            Departmentlist.setText("No department records found");
            return;
        }
        
        try
        {
            Scanner input = new Scanner (file);
            
            while (input.hasNextLine())
            {
                String line = input.nextLine();
                Departmentlist.append(line+"\n");
            }
            input.close();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this,"Unable to read department record");
        }
    }
    private boolean departmentIDExists(String departmentID)
    {
        File file = new File("department.txt");
        
        if(!file.exists())
        {
            return false;
        }
        
        try
        {
            Scanner input = new Scanner(file);
            
            while(input.hasNextLine())
            {
                String line = input.nextLine().trim();
                
                
                if(line.equalsIgnoreCase("DepartmentID:"+departmentID))
                {
                    input.close();
                    return true;
                }
            }
        input.close();
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(this,"Unable to read records");
        }
        return false;
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageDepartment().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Departmentlist;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
